# Generated by Django 3.1 on 2020-08-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
