# Generated by Django 3.1 on 2020-08-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
