# Generated by Django 3.1 on 2020-08-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
